# The name of the trap contract to be deployed.
name = "VolatileCollateralVelocityTrap"

# The path to the Solidity file containing the trap contract.
# This is relative to the project root.
source = "src/VolatileCollateralVelocityTrap.sol"

# The constructor arguments for the trap contract.
# The user said no constructor args, so this should be empty.
constructor_args = []

# The network to deploy to.
network = "hoodi"

# The address of the response contract.
# This will be deployed separately with Foundry.
response_contract_address = "0x..." # Placeholder

# The ABI of the shouldRespond function.
should_respond_abi = "function shouldRespond(bytes[] calldata data) external pure returns (bool, bytes memory)"
