# The name of the trap contract to be deployed.
name = "VolatileCollateralVelocityTrap"

# The path to the Solidity file containing the trap contract.
# This is relative to the project root.
source = "src/VolatileCollateralVelocityTrap.sol"

# The network to deploy to.
network = "hoodi"

# The address of the response contract.
response_contract_address = "0x..." # Placeholder: Deploy TrapResponse and update this

# The function signature for the response contract.
response_function = "executeResponse(bytes)"

# Drosera operator settings
private_trap = true
whitelist = ["0x..." # Placeholder: Add your operator address here]

# Number of blocks to sample for shouldRespond
block_sample_size = 2